; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
monitor_filters = default, log2file
board_build.f_cpu = 240000000L
build_flags = 
    -DEIGEN_NO_DEBUG
    -DEIGEN_DONT_VECTORIZE
    -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT
    -std=gnu++17
	-O3
	-ffast-math
	-funroll-loops
lib_deps =
	hideakitai/ArduinoEigen @ ^0.2.2
	arduino-libraries/Madgwick@^1.2.0
	adafruit/Adafruit MPU6050@^2.2.6