; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L   ; Configura para 240MHz
build_flags = -O3
lib_deps = 
	bolderflight/Bolder Flight Systems MPU9250@^1.0.2
	arduino-libraries/Madgwick@^1.2.0

; --- Para configurar Otimizações de Compilação ---
; Você pode adicionar flags de compilação diretamente.
; -Os: Otimizar para tamanho (padrão em muitos casos no Arduino)
; -O1: Otimização mínima
; -O2: Otimização balanceada para velocidade e tamanho
; -O3: Otimização agressiva para velocidade (pode aumentar o tamanho do código significativamente)
; -Ofast: -O3 com algumas otimizações adicionais que podem não ser estritamente compatíveis com o padrão IEEE.
;
; Para substituir o padrão ou adicionar/modificar flags:

